-- ============================================
-- Trading Strategy Intelligence Database Schema
-- ============================================
-- Designed for SQLite with PostgreSQL migration compatibility
-- Database: strategy-intelligence.db
-- Version: 1.0.0

-- Enable foreign key support
PRAGMA foreign_keys = ON;

-- ============================================
-- Table: strategies
-- Stores trading strategies with their rules and parameters
-- ============================================
CREATE TABLE IF NOT EXISTS strategies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    source VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    description TEXT,
    entry_rules JSON,
    exit_rules JSON,
    risk_params JSON,
    performance_metrics JSON,
    confidence_score DECIMAL(5,2),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- Table: signals
-- Trading signals generated by strategies
-- ============================================
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token_symbol VARCHAR(50) NOT NULL,
    strategy_id INTEGER,
    signal_type VARCHAR(20) NOT NULL,
    entry_price DECIMAL(18,8),
    target_price DECIMAL(18,8),
    stop_loss DECIMAL(18,8),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(100) NOT NULL,
    confidence DECIMAL(5,2),
    executed BOOLEAN DEFAULT 0,
    execution_price DECIMAL(18,8),
    execution_time DATETIME,
    pnl DECIMAL(18,8),
    notes TEXT,
    FOREIGN KEY (strategy_id) REFERENCES strategies(id) ON DELETE SET NULL
);

-- ============================================
-- Table: smart_money
-- Tracks whale and smart money movements
-- ============================================
CREATE TABLE IF NOT EXISTS smart_money (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    wallet_address VARCHAR(255) NOT NULL,
    entity_name VARCHAR(255),
    token_symbol VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    amount DECIMAL(24,8) NOT NULL,
    amount_usd DECIMAL(18,2),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    tx_hash VARCHAR(255) NOT NULL,
    chain VARCHAR(50) NOT NULL,
    strategy_correlation INTEGER,
    signal_generated BOOLEAN DEFAULT 0,
    block_number BIGINT,
    gas_price_gwei DECIMAL(18,4),
    FOREIGN KEY (strategy_correlation) REFERENCES strategies(id) ON DELETE SET NULL
);

-- ============================================
-- Table: market_context
-- Market sentiment and conditions snapshot
-- ============================================
CREATE TABLE IF NOT EXISTS market_context (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fear_greed_index INTEGER,
    fear_greed_classification VARCHAR(20),
    btc_dominance DECIMAL(5,2),
    eth_dominance DECIMAL(5,2),
    total_market_cap_usd DECIMAL(20,2),
    btc_price DECIMAL(18,2),
    eth_price DECIMAL(18,2),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    narrative TEXT,
    trending_topics JSON,
    volatility_index DECIMAL(8,4),
    funding_rates JSON,
    liquidation_data JSON
);

-- ============================================
-- Table: strategy_performance
-- Aggregated performance metrics for each strategy
-- ============================================
CREATE TABLE IF NOT EXISTS strategy_performance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id INTEGER NOT NULL,
    win_count INTEGER DEFAULT 0,
    loss_count INTEGER DEFAULT 0,
    break_even_count INTEGER DEFAULT 0,
    avg_profit DECIMAL(18,8) DEFAULT 0,
    avg_loss DECIMAL(18,8) DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    win_rate DECIMAL(5,2),
    profit_factor DECIMAL(8,4),
    sharpe_ratio DECIMAL(8,4),
    max_drawdown DECIMAL(8,4),
    total_pnl DECIMAL(18,8) DEFAULT 0,
    avg_trade_duration_hours DECIMAL(10,2),
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    period_start DATE,
    period_end DATE,
    FOREIGN KEY (strategy_id) REFERENCES strategies(id) ON DELETE CASCADE,
    UNIQUE(strategy_id, period_start)
);

-- ============================================
-- INDEXES for Performance Optimization
-- ============================================

-- Strategies indexes
CREATE INDEX IF NOT EXISTS idx_strategies_source ON strategies(source);
CREATE INDEX IF NOT EXISTS idx_strategies_type ON strategies(type);
CREATE INDEX IF NOT EXISTS idx_strategies_confidence ON strategies(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_strategies_created ON strategies(created_at DESC);

-- Signals indexes
CREATE INDEX IF NOT EXISTS idx_signals_token ON signals(token_symbol);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_id);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_signals_executed ON signals(executed);
CREATE INDEX IF NOT EXISTS idx_signals_confidence ON signals(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_signals_token_timestamp ON signals(token_symbol, timestamp DESC);

-- Smart money indexes
CREATE INDEX IF NOT EXISTS idx_smart_wallet ON smart_money(wallet_address);
CREATE INDEX IF NOT EXISTS idx_smart_token ON smart_money(token_symbol);
CREATE INDEX IF NOT EXISTS idx_smart_timestamp ON smart_money(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_smart_action ON smart_money(action);
CREATE INDEX IF NOT EXISTS idx_smart_entity ON smart_money(entity_name);
CREATE INDEX IF NOT EXISTS idx_smart_chain ON smart_money(chain);
CREATE INDEX IF NOT EXISTS idx_smart_amount ON smart_money(amount_usd DESC);

-- Market context indexes
CREATE INDEX IF NOT EXISTS idx_market_timestamp ON market_context(timestamp DESC);

-- Strategy performance indexes
CREATE INDEX IF NOT EXISTS idx_perf_strategy ON strategy_performance(strategy_id);
CREATE INDEX IF NOT EXISTS idx_perf_winrate ON strategy_performance(win_rate DESC);
CREATE INDEX IF NOT EXISTS idx_perf_pnl ON strategy_performance(total_pnl DESC);
